name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    
    # uses GitHub's checkout action to checkout code form the main branch
    - uses: actions/checkout@v3
    
    # sets up .NET 8 SDK
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

      # publishes Blazor project to the release-folder
    - name: Publish .NET Project
      run: dotnet publish arvidpm.github.io/arvidpm.github.io.csproj -c Release -o release --nologo

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
